### ISSUE TITLE
New distro

### ISSUE THREAD

**Issue by Krator3** [Coopydood/HyperFluent-GRUB-Theme#2]
Hello! This design is very interesting and beautiful, but I would like to ask you to make an option with Alt Linux. I know that the distribution is not very popular, but if you can make a beautiful theme for it, then its community will be very grateful to you!

P.S: Excuse my English

**Comment by Coopydood** [comment]
https://github.com/Coopydood/HyperFluent-GRUB-Theme/releases/tag/v1.0.1 :)
