### ISSUE TITLE
Zip files in releases have improper extension

### ISSUE THREAD

**Issue by ext4cats** [Coopydood/HyperFluent-GRUB-Theme#5]
Just wanted to let you know that the supposed `.tar.gz` files in the releases tab are actually zip files.

It took me a few hours of slamming my head into my desk to realize why `tar` wouldn't extract the files 🤔

![image](https://github.com/user-attachments/assets/babe8c39-69cb-4cc4-b3ee-c3f2cc315541)

**Comment by Coopydood** [comment]
Oh, thank you!

(And sorry for the headache...)
